// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mqtt} from '../models';
import {main} from '../models';

export function ClearConnectionData(arg1:string):Promise<void>;

export function Connect(arg1:mqtt.ConnectionConfig):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetTopicDetails(arg1:string,arg2:string):Promise<mqtt.TopicDetails>;

export function GetTopicHistory(arg1:string,arg2:string,arg3:number,arg4:any):Promise<Array<mqtt.MessageRecord>>;

export function GetTreeSnapshot(arg1:string):Promise<Array<mqtt.TopicUpdate>>;

export function LoadConnections():Promise<Array<mqtt.ConnectionConfig>>;

export function LoadLayout():Promise<main.StoredLayout>;

export function LoadSettings():Promise<main.AppSettings>;

export function LoadTrends():Promise<Array<main.Trend>>;

export function OpenFilePicker():Promise<string>;

export function Publish(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<void>;

export function SaveConnections(arg1:Array<mqtt.ConnectionConfig>):Promise<void>;

export function SaveLayout(arg1:main.StoredLayout):Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function SaveTrends(arg1:Array<main.Trend>):Promise<void>;

export function TestConnection(arg1:mqtt.ConnectionConfig):Promise<void>;

export function UnwatchTopic(arg1:string):Promise<void>;

export function UnwatchTrendTopic(arg1:string,arg2:string):Promise<void>;

export function WatchTopic(arg1:string,arg2:string):Promise<void>;

export function WatchTrendTopic(arg1:string,arg2:string):Promise<void>;
