// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConnectionData(arg1) {
  return window['go']['main']['App']['ClearConnectionData'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetTopicDetails(arg1, arg2) {
  return window['go']['main']['App']['GetTopicDetails'](arg1, arg2);
}

export function GetTopicHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTopicHistory'](arg1, arg2, arg3, arg4);
}

export function GetTreeSnapshot(arg1) {
  return window['go']['main']['App']['GetTreeSnapshot'](arg1);
}

export function LoadConnections() {
  return window['go']['main']['App']['LoadConnections']();
}

export function LoadLayout() {
  return window['go']['main']['App']['LoadLayout']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function LoadTrends() {
  return window['go']['main']['App']['LoadTrends']();
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}

export function Publish(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Publish'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveConnections(arg1) {
  return window['go']['main']['App']['SaveConnections'](arg1);
}

export function SaveLayout(arg1) {
  return window['go']['main']['App']['SaveLayout'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function SaveTrends(arg1) {
  return window['go']['main']['App']['SaveTrends'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UnwatchTopic(arg1) {
  return window['go']['main']['App']['UnwatchTopic'](arg1);
}

export function UnwatchTrendTopic(arg1, arg2) {
  return window['go']['main']['App']['UnwatchTrendTopic'](arg1, arg2);
}

export function WatchTopic(arg1, arg2) {
  return window['go']['main']['App']['WatchTopic'](arg1, arg2);
}

export function WatchTrendTopic(arg1, arg2) {
  return window['go']['main']['App']['WatchTrendTopic'](arg1, arg2);
}
